image: alpine:latest

pages:
  stage: deploy
  script:
  - echo "I am on gitlab-runner"
  - echo "Deploying to https://sde.pages.gitlab.data-services.tk/ui-prototype"
  artifacts:
    paths:
    - public
  only:
  - master
